/* soapStub.h
   Generated by gSOAP 2.7.9l from sugar.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_ns1__note_USCOREattachment
#define SOAP_TYPE_ns1__note_USCOREattachment (7)
/* ns1:note_attachment */
struct ns1__note_USCOREattachment
{
	char *id;	/* required element of type xsd:string */
	char *filename;	/* required element of type xsd:string */
	char *file;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__new_USCOREnote_USCOREattachment (8)
/* ns1:new_note_attachment */
struct ns1__new_USCOREnote_USCOREattachment
{
	char *id;	/* required element of type xsd:string */
	char *filename;	/* required element of type xsd:string */
	char *file;	/* required element of type xsd:string */
	char *related_USCOREmodule_USCOREid;	/* required element of type xsd:string */
	char *related_USCOREmodule_USCOREname;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREreturn_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__new_USCOREreturn_USCOREnote_USCOREattachment (9)
/* ns1:new_return_note_attachment */
struct ns1__new_USCOREreturn_USCOREnote_USCOREattachment
{
	struct ns1__new_USCOREnote_USCOREattachment *note_USCOREattachment;	/* required element of type ns1:new_note_attachment */
};
#endif

#ifndef SOAP_TYPE_ns1__return_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__return_USCOREnote_USCOREattachment (11)
/* ns1:return_note_attachment */
struct ns1__return_USCOREnote_USCOREattachment
{
	struct ns1__note_USCOREattachment *note_USCOREattachment;	/* required element of type ns1:note_attachment */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__user_USCOREauth
#define SOAP_TYPE_ns1__user_USCOREauth (15)
/* ns1:user_auth */
struct ns1__user_USCOREauth
{
	char *user_USCOREname;	/* required element of type xsd:string */
	char *password;	/* required element of type xsd:string */
	char *version;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__field
#define SOAP_TYPE_ns1__field (16)
/* ns1:field */
struct ns1__field
{
	char *name;	/* required element of type xsd:string */
	char *type;	/* required element of type xsd:string */
	char *label;	/* required element of type xsd:string */
	int required;	/* required element of type xsd:int */
	struct name_USCOREvalue_USCORElist *options;	/* required element of type ArrayOfname-value */
	char *default_USCOREvalue;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREfield
#define SOAP_TYPE_ns1__link_USCOREfield (19)
/* ns1:link_field */
struct ns1__link_USCOREfield
{
	char *name;	/* required element of type xsd:string */
	char *type;	/* required element of type xsd:string */
	char *relationship;	/* required element of type xsd:string */
	char *module;	/* required element of type xsd:string */
	char *bean_USCOREname;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__name_USCOREvalue
#define SOAP_TYPE_ns1__name_USCOREvalue (20)
/* ns1:name_value */
struct ns1__name_USCOREvalue
{
	char *name;	/* required element of type xsd:string */
	char *value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__module_USCOREfields
#define SOAP_TYPE_ns1__module_USCOREfields (21)
/* ns1:module_fields */
struct ns1__module_USCOREfields
{
	char *module_USCOREname;	/* required element of type xsd:string */
	struct field_USCORElist *module_USCOREfields;	/* required element of type ArrayOffield */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREmodule_USCOREfields
#define SOAP_TYPE_ns1__new_USCOREmodule_USCOREfields (24)
/* ns1:new_module_fields */
struct ns1__new_USCOREmodule_USCOREfields
{
	char *module_USCOREname;	/* required element of type xsd:string */
	struct field_USCORElist *module_USCOREfields;	/* required element of type ArrayOffield */
	struct link_USCOREfield_USCORElist *link_USCOREfields;	/* required element of type ArrayOflink-field */
};
#endif

#ifndef SOAP_TYPE_ns1__module_USCORElist
#define SOAP_TYPE_ns1__module_USCORElist (27)
/* ns1:module_list */
struct ns1__module_USCORElist
{
	struct select_USCOREfields *modules;	/* required element of type ArrayOfstring */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__error_USCOREvalue
#define SOAP_TYPE_ns1__error_USCOREvalue (13)
/* ns1:error_value */
struct ns1__error_USCOREvalue
{
	char *number;	/* required element of type xsd:string */
	char *name;	/* required element of type xsd:string */
	char *description;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__entry_USCOREvalue
#define SOAP_TYPE_ns1__entry_USCOREvalue (30)
/* ns1:entry_value */
struct ns1__entry_USCOREvalue
{
	char *id;	/* required element of type xsd:string */
	char *module_USCOREname;	/* required element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* required element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument_USCOREresult (31)
/* ns1:get_mailmerge_document_result */
struct ns1__get_USCOREmailmerge_USCOREdocument_USCOREresult
{
	char *html;	/* required element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* required element of type ArrayOfname-value */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray
#define SOAP_TYPE_ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray (32)
/* ns1:link_name_to_fields_array */
struct ns1__link_USCOREname_USCOREto_USCOREfields_USCOREarray
{
	char *name;	/* required element of type xsd:string */
	struct select_USCOREfields *value;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__link_USCOREname_USCOREvalue
#define SOAP_TYPE_ns1__link_USCOREname_USCOREvalue (33)
/* ns1:link_name_value */
struct ns1__link_USCOREname_USCOREvalue
{
	char *name;	/* required element of type xsd:string */
	struct link_USCOREarray_USCORElist *records;	/* required element of type ArrayOfArrayOfArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCOREresult_USCOREversion2
#define SOAP_TYPE_ns1__get_USCOREentry_USCOREresult_USCOREversion2 (36)
/* ns1:get_entry_result_version2 */
struct ns1__get_USCOREentry_USCOREresult_USCOREversion2
{
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
	struct link_USCORElists *relationship_USCORElist;	/* required element of type ArrayOfArrayOflink-name-value */
};
#endif

#ifndef SOAP_TYPE_ns1__return_USCOREsearch_USCOREresult
#define SOAP_TYPE_ns1__return_USCOREsearch_USCOREresult (41)
/* ns1:return_search_result */
struct ns1__return_USCOREsearch_USCOREresult
{
	struct link_USCORElist *entry_USCORElist;	/* required element of type ArrayOflink-name-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult (44)
/* ns1:get_entry_list_result */
struct ns1__get_USCOREentry_USCORElist_USCOREresult
{
	int result_USCOREcount;	/* required element of type xsd:int */
	int next_USCOREoffset;	/* required element of type xsd:int */
	struct field_USCORElist *field_USCORElist;	/* required element of type ArrayOffield */
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2 (45)
/* ns1:get_entry_list_result_version2 */
struct ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREversion2
{
	int result_USCOREcount;	/* required element of type xsd:int */
	int next_USCOREoffset;	/* required element of type xsd:int */
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
	struct link_USCORElists *relationship_USCORElist;	/* required element of type ArrayOfArrayOflink-name-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREentry_USCOREresult (46)
/* ns1:get_entry_result */
struct ns1__get_USCOREentry_USCOREresult
{
	struct field_USCORElist *field_USCORElist;	/* required element of type ArrayOffield */
	struct entry_USCORElist *entry_USCORElist;	/* required element of type ArrayOfentry-value */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREinfo_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREinfo_USCOREresult (47)
/* ns1:get_server_info_result */
struct ns1__get_USCOREserver_USCOREinfo_USCOREresult
{
	char *flavor;	/* required element of type xsd:string */
	char *version;	/* required element of type xsd:string */
	char *gmt_USCOREtime;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentry_USCOREresult
#define SOAP_TYPE_ns1__set_USCOREentry_USCOREresult (48)
/* ns1:set_entry_result */
struct ns1__set_USCOREentry_USCOREresult
{
	char *id;	/* required element of type xsd:string */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREset_USCOREentry_USCOREresult
#define SOAP_TYPE_ns1__new_USCOREset_USCOREentry_USCOREresult (49)
/* ns1:new_set_entry_result */
struct ns1__new_USCOREset_USCOREentry_USCOREresult
{
	char *id;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREset_USCOREentries_USCOREresult
#define SOAP_TYPE_ns1__new_USCOREset_USCOREentries_USCOREresult (50)
/* ns1:new_set_entries_result */
struct ns1__new_USCOREset_USCOREentries_USCOREresult
{
	struct select_USCOREfields *ids;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries_USCOREresult
#define SOAP_TYPE_ns1__set_USCOREentries_USCOREresult (51)
/* ns1:set_entries_result */
struct ns1__set_USCOREentries_USCOREresult
{
	struct select_USCOREfields *ids;	/* required element of type ArrayOfstring */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__id_USCOREmod
#define SOAP_TYPE_ns1__id_USCOREmod (52)
/* ns1:id_mod */
struct ns1__id_USCOREmod
{
	char *id;	/* required element of type xsd:string */
	char *date_USCOREmodified;	/* required element of type xsd:string */
	int deleted;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelationships_USCOREresult
#define SOAP_TYPE_ns1__get_USCORErelationships_USCOREresult (53)
/* ns1:get_relationships_result */
struct ns1__get_USCORErelationships_USCOREresult
{
	struct ids_USCOREmods *ids;	/* required element of type ArrayOfid-mod */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationship_USCOREvalue
#define SOAP_TYPE_ns1__set_USCORErelationship_USCOREvalue (56)
/* ns1:set_relationship_value */
struct ns1__set_USCORErelationship_USCOREvalue
{
	char *module1;	/* required element of type xsd:string */
	char *module1_USCOREid;	/* required element of type xsd:string */
	char *module2;	/* required element of type xsd:string */
	char *module2_USCOREid;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult
#define SOAP_TYPE_ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult (57)
/* ns1:new_set_relationship_list_result */
struct ns1__new_USCOREset_USCORErelationship_USCORElist_USCOREresult
{
	int created;	/* required element of type xsd:int */
	int failed;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationship_USCORElist_USCOREresult
#define SOAP_TYPE_ns1__set_USCORErelationship_USCORElist_USCOREresult (58)
/* ns1:set_relationship_list_result */
struct ns1__set_USCORErelationship_USCORElist_USCOREresult
{
	int created;	/* required element of type xsd:int */
	int failed;	/* required element of type xsd:int */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__document_USCORErevision
#define SOAP_TYPE_ns1__document_USCORErevision (59)
/* ns1:document_revision */
struct ns1__document_USCORErevision
{
	char *id;	/* required element of type xsd:string */
	char *document_USCOREname;	/* required element of type xsd:string */
	char *revision;	/* required element of type xsd:string */
	char *filename;	/* required element of type xsd:string */
	char *file;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREencoded
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREencoded (60)
/* ns1:get_entry_list_result_encoded */
struct ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREencoded
{
	int result_USCOREcount;	/* required element of type xsd:int */
	int next_USCOREoffset;	/* required element of type xsd:int */
	int total_USCOREcount;	/* required element of type xsd:int */
	struct select_USCOREfields *field_USCORElist;	/* required element of type ArrayOfstring */
	char *entry_USCORElist;	/* required element of type xsd:string */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREsync_USCOREresult_USCOREencoded
#define SOAP_TYPE_ns1__get_USCOREsync_USCOREresult_USCOREencoded (61)
/* ns1:get_sync_result_encoded */
struct ns1__get_USCOREsync_USCOREresult_USCOREencoded
{
	char *result;	/* required element of type xsd:string */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREquick_USCOREsync_USCOREresult_USCOREencoded
#define SOAP_TYPE_ns1__get_USCOREquick_USCOREsync_USCOREresult_USCOREencoded (62)
/* ns1:get_quick_sync_result_encoded */
struct ns1__get_USCOREquick_USCOREsync_USCOREresult_USCOREencoded
{
	char *result;	/* required element of type xsd:string */
	int result_USCOREcount;	/* required element of type xsd:int */
	int next_USCOREoffset;	/* required element of type xsd:int */
	int total_USCOREcount;	/* required element of type xsd:int */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__return_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__return_USCOREdocument_USCORErevision (63)
/* ns1:return_document_revision */
struct ns1__return_USCOREdocument_USCORErevision
{
	struct ns1__document_USCORErevision *document_USCORErevision;	/* required element of type ns1:document_revision */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__new_USCOREreturn_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__new_USCOREreturn_USCOREdocument_USCORErevision (65)
/* ns1:new_return_document_revision */
struct ns1__new_USCOREreturn_USCOREdocument_USCORErevision
{
	struct ns1__document_USCORErevision *document_USCORErevision;	/* required element of type ns1:document_revision */
};
#endif

#ifndef SOAP_TYPE_ns1__name_USCOREvalue_USCOREoperator
#define SOAP_TYPE_ns1__name_USCOREvalue_USCOREoperator (66)
/* ns1:name_value_operator */
struct ns1__name_USCOREvalue_USCOREoperator
{
	char *name;	/* required element of type xsd:string */
	char *value;	/* required element of type xsd:string */
	char *operator_;	/* required element of type xsd:string */
	struct select_USCOREfields *value_USCOREarray;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__newsletter
#define SOAP_TYPE_ns1__newsletter (67)
/* ns1:newsletter */
struct ns1__newsletter
{
	char *name;	/* required element of type xsd:string */
	char *prospect_USCORElist_USCOREid;	/* required element of type xsd:string */
	char *campaign_USCOREid;	/* required element of type xsd:string */
	char *description;	/* required element of type xsd:string */
	char *frequency;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREsubscription_USCORElists_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREsubscription_USCORElists_USCOREresult (68)
/* ns1:get_subscription_lists_result */
struct ns1__get_USCOREsubscription_USCORElists_USCOREresult
{
	struct newsletter_USCORElist *unsubscribed;	/* required element of type ArrayOfnewsletter */
	struct newsletter_USCORElist *subscribed;	/* required element of type ArrayOfnewsletter */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__name_USCOREvalue_USCORElists_USCOREerror
#define SOAP_TYPE_ns1__name_USCOREvalue_USCORElists_USCOREerror (71)
/* ns1:name_value_lists_error */
struct ns1__name_USCOREvalue_USCORElists_USCOREerror
{
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* required element of type ArrayOfArrayOfname-value */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries_USCOREcount_USCOREresult
#define SOAP_TYPE_ns1__get_USCOREentries_USCOREcount_USCOREresult (74)
/* ns1:get_entries_count_result */
struct ns1__get_USCOREentries_USCOREcount_USCOREresult
{
	int result_USCOREcount;	/* required element of type xsd:int */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries_USCOREdetail_USCOREresult
#define SOAP_TYPE_ns1__set_USCOREentries_USCOREdetail_USCOREresult (75)
/* ns1:set_entries_detail_result */
struct ns1__set_USCOREentries_USCOREdetail_USCOREresult
{
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* required element of type ArrayOfArrayOfname-value */
	struct ns1__error_USCOREvalue *error;	/* required element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__contact_USCOREdetail
#define SOAP_TYPE_ns1__contact_USCOREdetail (76)
/* ns1:contact_detail */
struct ns1__contact_USCOREdetail
{
	char *email_USCOREaddress;	/* required element of type xsd:string */
	char *name1;	/* required element of type xsd:string */
	char *name2;	/* required element of type xsd:string */
	char *association;	/* required element of type xsd:string */
	char *id;	/* required element of type xsd:string */
	char *msi_USCOREid;	/* required element of type xsd:string */
	char *type;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__user_USCOREdetail
#define SOAP_TYPE_ns1__user_USCOREdetail (77)
/* ns1:user_detail */
struct ns1__user_USCOREdetail
{
	char *email_USCOREaddress;	/* required element of type xsd:string */
	char *user_USCOREname;	/* required element of type xsd:string */
	char *first_USCOREname;	/* required element of type xsd:string */
	char *last_USCOREname;	/* required element of type xsd:string */
	char *department;	/* required element of type xsd:string */
	char *id;	/* required element of type xsd:string */
	char *title;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_field_USCORElist
#define SOAP_TYPE_field_USCORElist (22)
/* SOAP encoded array of ns1:field schema type: */
struct field_USCORElist
{
	struct ns1__field **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREfield_USCORElist
#define SOAP_TYPE_link_USCOREfield_USCORElist (25)
/* SOAP encoded array of ns1:link_field schema type: */
struct link_USCOREfield_USCORElist
{
	struct ns1__link_USCOREfield **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_name_USCOREvalue_USCORElist
#define SOAP_TYPE_name_USCOREvalue_USCORElist (17)
/* SOAP encoded array of ns1:name_value schema type: */
struct name_USCOREvalue_USCORElist
{
	struct ns1__name_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_name_USCOREvalue_USCORElists
#define SOAP_TYPE_name_USCOREvalue_USCORElists (72)
/* SOAP encoded array of ns1:name_value schema type: */
struct name_USCOREvalue_USCORElists
{
	struct name_USCOREvalue_USCORElist **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_select_USCOREfields
#define SOAP_TYPE_select_USCOREfields (28)
/* SOAP encoded array of xsd:string schema type: */
struct select_USCOREfields
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_entry_USCORElist
#define SOAP_TYPE_entry_USCORElist (37)
/* SOAP encoded array of ns1:entry_value schema type: */
struct entry_USCORElist
{
	struct ns1__entry_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREvalue
#define SOAP_TYPE_link_USCOREvalue (88)
/* SOAP encoded array of ns1:name_value schema type: */
struct link_USCOREvalue
{
	struct name_USCOREvalue_USCORElist **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCOREarray_USCORElist
#define SOAP_TYPE_link_USCOREarray_USCORElist (34)
/* SOAP encoded array of ns1:name_value schema type: */
struct link_USCOREarray_USCORElist
{
	struct link_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCORElist
#define SOAP_TYPE_link_USCORElist (42)
/* SOAP encoded array of ns1:link_name_value schema type: */
struct link_USCORElist
{
	struct ns1__link_USCOREname_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_link_USCORElists
#define SOAP_TYPE_link_USCORElists (39)
/* SOAP encoded array of ns1:link_name_value schema type: */
struct link_USCORElists
{
	struct link_USCORElist **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ids_USCOREmods
#define SOAP_TYPE_ids_USCOREmods (54)
/* SOAP encoded array of ns1:id_mod schema type: */
struct ids_USCOREmods
{
	struct ns1__id_USCOREmod **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_set_USCORErelationship_USCORElist
#define SOAP_TYPE_set_USCORErelationship_USCORElist (96)
/* SOAP encoded array of ns1:set_relationship_value schema type: */
struct set_USCORErelationship_USCORElist
{
	struct ns1__set_USCORErelationship_USCOREvalue **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_new_USCOREset_USCORErelationhip_USCOREids
#define SOAP_TYPE_new_USCOREset_USCORErelationhip_USCOREids (99)
/* SOAP encoded array of xsd:string schema type: */
struct new_USCOREset_USCORErelationhip_USCOREids
{
	struct select_USCOREfields **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_name_USCOREvalue_USCOREoperator_USCORElist
#define SOAP_TYPE_name_USCOREvalue_USCOREoperator_USCORElist (101)
/* SOAP encoded array of ns1:name_value_operator schema type: */
struct name_USCOREvalue_USCOREoperator_USCORElist
{
	struct ns1__name_USCOREvalue_USCOREoperator **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_newsletter_USCORElist
#define SOAP_TYPE_newsletter_USCORElist (69)
/* SOAP encoded array of ns1:newsletter schema type: */
struct newsletter_USCORElist
{
	struct ns1__newsletter **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_str_USCOREarray
#define SOAP_TYPE_str_USCOREarray (106)
/* SOAP encoded array of xsd:string schema type: */
struct str_USCOREarray
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_contact_USCOREdetail_USCOREarray
#define SOAP_TYPE_contact_USCOREdetail_USCOREarray (107)
/* SOAP encoded array of ns1:contact_detail schema type: */
struct contact_USCOREdetail_USCOREarray
{
	struct ns1__contact_USCOREdetail **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_user_USCOREdetail_USCOREarray
#define SOAP_TYPE_user_USCOREdetail_USCOREarray (110)
/* SOAP encoded array of ns1:user_detail schema type: */
struct user_USCOREdetail_USCOREarray
{
	struct ns1__user_USCOREdetail **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__is_USCOREuser_USCOREadminResponse
#define SOAP_TYPE_ns1__is_USCOREuser_USCOREadminResponse (115)
/* ns1:is_user_adminResponse */
struct ns1__is_USCOREuser_USCOREadminResponse
{
	int *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__is_USCOREuser_USCOREadmin
#define SOAP_TYPE_ns1__is_USCOREuser_USCOREadmin (116)
/* ns1:is_user_admin */
struct ns1__is_USCOREuser_USCOREadmin
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__loginResponse
#define SOAP_TYPE_ns1__loginResponse (117)
/* ns1:loginResponse */
struct ns1__loginResponse
{
	struct ns1__set_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__login
#define SOAP_TYPE_ns1__login (122)
/* ns1:login */
struct ns1__login
{
	struct ns1__user_USCOREauth *user_USCOREauth;	/* optional element of type ns1:user_auth */
	char *application_USCOREname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__is_USCOREloopbackResponse
#define SOAP_TYPE_ns1__is_USCOREloopbackResponse (124)
/* ns1:is_loopbackResponse */
struct ns1__is_USCOREloopbackResponse
{
	int *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__is_USCOREloopback
#define SOAP_TYPE_ns1__is_USCOREloopback (125)
/* ns1:is_loopback */
struct ns1__is_USCOREloopback
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__seamless_USCOREloginResponse
#define SOAP_TYPE_ns1__seamless_USCOREloginResponse (127)
/* ns1:seamless_loginResponse */
struct ns1__seamless_USCOREloginResponse
{
	int *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__seamless_USCORElogin
#define SOAP_TYPE_ns1__seamless_USCORElogin (128)
/* ns1:seamless_login */
struct ns1__seamless_USCORElogin
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElistResponse
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElistResponse (129)
/* ns1:get_entry_listResponse */
struct ns1__get_USCOREentry_USCORElistResponse
{
	struct ns1__get_USCOREentry_USCORElist_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_list_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry_USCORElist
#define SOAP_TYPE_ns1__get_USCOREentry_USCORElist (133)
/* ns1:get_entry_list */
struct ns1__get_USCOREentry_USCORElist
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *query;	/* optional element of type xsd:string */
	char *order_USCOREby;	/* optional element of type xsd:string */
	int offset;	/* required element of type xsd:int */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	int max_USCOREresults;	/* required element of type xsd:int */
	int deleted;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentryResponse
#define SOAP_TYPE_ns1__get_USCOREentryResponse (134)
/* ns1:get_entryResponse */
struct ns1__get_USCOREentryResponse
{
	struct ns1__get_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentry
#define SOAP_TYPE_ns1__get_USCOREentry (138)
/* ns1:get_entry */
struct ns1__get_USCOREentry
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentriesResponse
#define SOAP_TYPE_ns1__get_USCOREentriesResponse (139)
/* ns1:get_entriesResponse */
struct ns1__get_USCOREentriesResponse
{
	struct ns1__get_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries
#define SOAP_TYPE_ns1__get_USCOREentries (142)
/* ns1:get_entries */
struct ns1__get_USCOREentries
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *ids;	/* optional element of type ArrayOfstring */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentryResponse
#define SOAP_TYPE_ns1__set_USCOREentryResponse (143)
/* ns1:set_entryResponse */
struct ns1__set_USCOREentryResponse
{
	struct ns1__set_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentry
#define SOAP_TYPE_ns1__set_USCOREentry (146)
/* ns1:set_entry */
struct ns1__set_USCOREentry
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* optional element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentriesResponse
#define SOAP_TYPE_ns1__set_USCOREentriesResponse (147)
/* ns1:set_entriesResponse */
struct ns1__set_USCOREentriesResponse
{
	struct ns1__set_USCOREentries_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_entries_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries
#define SOAP_TYPE_ns1__set_USCOREentries (151)
/* ns1:set_entries */
struct ns1__set_USCOREentries
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* optional element of type ArrayOfArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREnote_USCOREattachmentResponse
#define SOAP_TYPE_ns1__set_USCOREnote_USCOREattachmentResponse (152)
/* ns1:set_note_attachmentResponse */
struct ns1__set_USCOREnote_USCOREattachmentResponse
{
	struct ns1__set_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__set_USCOREnote_USCOREattachment (155)
/* ns1:set_note_attachment */
struct ns1__set_USCOREnote_USCOREattachment
{
	char *session;	/* optional element of type xsd:string */
	struct ns1__note_USCOREattachment *note;	/* optional element of type ns1:note_attachment */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREnote_USCOREattachmentResponse
#define SOAP_TYPE_ns1__get_USCOREnote_USCOREattachmentResponse (156)
/* ns1:get_note_attachmentResponse */
struct ns1__get_USCOREnote_USCOREattachmentResponse
{
	struct ns1__return_USCOREnote_USCOREattachment *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:return_note_attachment */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREnote_USCOREattachment
#define SOAP_TYPE_ns1__get_USCOREnote_USCOREattachment (160)
/* ns1:get_note_attachment */
struct ns1__get_USCOREnote_USCOREattachment
{
	char *session;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__relate_USCOREnote_USCOREto_USCOREmoduleResponse
#define SOAP_TYPE_ns1__relate_USCOREnote_USCOREto_USCOREmoduleResponse (161)
/* ns1:relate_note_to_moduleResponse */
struct ns1__relate_USCOREnote_USCOREto_USCOREmoduleResponse
{
	struct ns1__error_USCOREvalue *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__relate_USCOREnote_USCOREto_USCOREmodule
#define SOAP_TYPE_ns1__relate_USCOREnote_USCOREto_USCOREmodule (164)
/* ns1:relate_note_to_module */
struct ns1__relate_USCOREnote_USCOREto_USCOREmodule
{
	char *session;	/* optional element of type xsd:string */
	char *note_USCOREid;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *module_USCOREid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelated_USCOREnotesResponse
#define SOAP_TYPE_ns1__get_USCORErelated_USCOREnotesResponse (165)
/* ns1:get_related_notesResponse */
struct ns1__get_USCORErelated_USCOREnotesResponse
{
	struct ns1__get_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelated_USCOREnotes
#define SOAP_TYPE_ns1__get_USCORErelated_USCOREnotes (168)
/* ns1:get_related_notes */
struct ns1__get_USCORErelated_USCOREnotes
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *module_USCOREid;	/* optional element of type xsd:string */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__logoutResponse
#define SOAP_TYPE_ns1__logoutResponse (169)
/* ns1:logoutResponse */
struct ns1__logoutResponse
{
	struct ns1__error_USCOREvalue *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__logout
#define SOAP_TYPE_ns1__logout (172)
/* ns1:logout */
struct ns1__logout
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodule_USCOREfieldsResponse
#define SOAP_TYPE_ns1__get_USCOREmodule_USCOREfieldsResponse (173)
/* ns1:get_module_fieldsResponse */
struct ns1__get_USCOREmodule_USCOREfieldsResponse
{
	struct ns1__module_USCOREfields *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:module_fields */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields
#define SOAP_TYPE_ns1__get_USCOREmodule_USCOREfields (177)
/* ns1:get_module_fields */
struct ns1__get_USCOREmodule_USCOREfields
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodulesResponse
#define SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodulesResponse (178)
/* ns1:get_available_modulesResponse */
struct ns1__get_USCOREavailable_USCOREmodulesResponse
{
	struct ns1__module_USCORElist *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:module_list */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodules
#define SOAP_TYPE_ns1__get_USCOREavailable_USCOREmodules (182)
/* ns1:get_available_modules */
struct ns1__get_USCOREavailable_USCOREmodules
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__update_USCOREportal_USCOREuserResponse
#define SOAP_TYPE_ns1__update_USCOREportal_USCOREuserResponse (183)
/* ns1:update_portal_userResponse */
struct ns1__update_USCOREportal_USCOREuserResponse
{
	struct ns1__error_USCOREvalue *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__update_USCOREportal_USCOREuser
#define SOAP_TYPE_ns1__update_USCOREportal_USCOREuser (186)
/* ns1:update_portal_user */
struct ns1__update_USCOREportal_USCOREuser
{
	char *session;	/* optional element of type xsd:string */
	char *portal_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist;	/* optional element of type ArrayOfname-value */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREidResponse
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREidResponse (188)
/* ns1:get_user_idResponse */
struct ns1__get_USCOREuser_USCOREidResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREid
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREid (189)
/* ns1:get_user_id */
struct ns1__get_USCOREuser_USCOREid
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREidResponse
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREidResponse (191)
/* ns1:get_user_team_idResponse */
struct ns1__get_USCOREuser_USCOREteam_USCOREidResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREid
#define SOAP_TYPE_ns1__get_USCOREuser_USCOREteam_USCOREid (192)
/* ns1:get_user_team_id */
struct ns1__get_USCOREuser_USCOREteam_USCOREid
{
	char *session;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREtimeResponse
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREtimeResponse (194)
/* ns1:get_server_timeResponse */
struct ns1__get_USCOREserver_USCOREtimeResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREtime
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREtime (195)
/* ns1:get_server_time */
struct ns1__get_USCOREserver_USCOREtime
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREgmt_USCOREtimeResponse
#define SOAP_TYPE_ns1__get_USCOREgmt_USCOREtimeResponse (197)
/* ns1:get_gmt_timeResponse */
struct ns1__get_USCOREgmt_USCOREtimeResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREgmt_USCOREtime
#define SOAP_TYPE_ns1__get_USCOREgmt_USCOREtime (198)
/* ns1:get_gmt_time */
struct ns1__get_USCOREgmt_USCOREtime
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREsugar_USCOREflavorResponse
#define SOAP_TYPE_ns1__get_USCOREsugar_USCOREflavorResponse (200)
/* ns1:get_sugar_flavorResponse */
struct ns1__get_USCOREsugar_USCOREflavorResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREsugar_USCOREflavor
#define SOAP_TYPE_ns1__get_USCOREsugar_USCOREflavor (201)
/* ns1:get_sugar_flavor */
struct ns1__get_USCOREsugar_USCOREflavor
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREversionResponse
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREversionResponse (203)
/* ns1:get_server_versionResponse */
struct ns1__get_USCOREserver_USCOREversionResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREserver_USCOREversion
#define SOAP_TYPE_ns1__get_USCOREserver_USCOREversion (204)
/* ns1:get_server_version */
struct ns1__get_USCOREserver_USCOREversion
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__get_USCORErelationshipsResponse (205)
/* ns1:get_relationshipsResponse */
struct ns1__get_USCORErelationshipsResponse
{
	struct ns1__get_USCORErelationships_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_relationships_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCORErelationships
#define SOAP_TYPE_ns1__get_USCORErelationships (209)
/* ns1:get_relationships */
struct ns1__get_USCORErelationships
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *module_USCOREid;	/* optional element of type xsd:string */
	char *related_USCOREmodule;	/* optional element of type xsd:string */
	char *related_USCOREmodule_USCOREquery;	/* optional element of type xsd:string */
	int deleted;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationshipResponse
#define SOAP_TYPE_ns1__set_USCORErelationshipResponse (210)
/* ns1:set_relationshipResponse */
struct ns1__set_USCORErelationshipResponse
{
	struct ns1__error_USCOREvalue *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationship
#define SOAP_TYPE_ns1__set_USCORErelationship (213)
/* ns1:set_relationship */
struct ns1__set_USCORErelationship
{
	char *session;	/* optional element of type xsd:string */
	struct ns1__set_USCORErelationship_USCOREvalue *set_USCORErelationship_USCOREvalue;	/* optional element of type ns1:set_relationship_value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__set_USCORErelationshipsResponse (214)
/* ns1:set_relationshipsResponse */
struct ns1__set_USCORErelationshipsResponse
{
	struct ns1__set_USCORErelationship_USCORElist_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_relationship_list_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCORErelationships
#define SOAP_TYPE_ns1__set_USCORErelationships (219)
/* ns1:set_relationships */
struct ns1__set_USCORErelationships
{
	char *session;	/* optional element of type xsd:string */
	struct set_USCORErelationship_USCORElist *set_USCORErelationship_USCORElist;	/* optional element of type ArrayOfset-relationship-value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREdocument_USCORErevisionResponse
#define SOAP_TYPE_ns1__set_USCOREdocument_USCORErevisionResponse (220)
/* ns1:set_document_revisionResponse */
struct ns1__set_USCOREdocument_USCORErevisionResponse
{
	struct ns1__set_USCOREentry_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_entry_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__set_USCOREdocument_USCORErevision (223)
/* ns1:set_document_revision */
struct ns1__set_USCOREdocument_USCORErevision
{
	char *session;	/* optional element of type xsd:string */
	struct ns1__document_USCORErevision *note;	/* optional element of type ns1:document_revision */
};
#endif

#ifndef SOAP_TYPE_ns1__search_USCOREby_USCOREmoduleResponse
#define SOAP_TYPE_ns1__search_USCOREby_USCOREmoduleResponse (224)
/* ns1:search_by_moduleResponse */
struct ns1__search_USCOREby_USCOREmoduleResponse
{
	struct ns1__get_USCOREentry_USCORElist_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_list_result */
};
#endif

#ifndef SOAP_TYPE_ns1__search_USCOREby_USCOREmodule
#define SOAP_TYPE_ns1__search_USCOREby_USCOREmodule (227)
/* ns1:search_by_module */
struct ns1__search_USCOREby_USCOREmodule
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *search_USCOREstring;	/* optional element of type xsd:string */
	struct select_USCOREfields *modules;	/* optional element of type ArrayOfstring */
	int offset;	/* required element of type xsd:int */
	int max_USCOREresults;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocumentResponse
#define SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocumentResponse (228)
/* ns1:get_mailmerge_documentResponse */
struct ns1__get_USCOREmailmerge_USCOREdocumentResponse
{
	struct ns1__get_USCOREsync_USCOREresult_USCOREencoded *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_sync_result_encoded */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument
#define SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument (232)
/* ns1:get_mailmerge_document */
struct ns1__get_USCOREmailmerge_USCOREdocument
{
	char *session;	/* optional element of type xsd:string */
	char *file_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *fields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument2Response
#define SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument2Response (233)
/* ns1:get_mailmerge_document2Response */
struct ns1__get_USCOREmailmerge_USCOREdocument2Response
{
	struct ns1__get_USCOREmailmerge_USCOREdocument_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_mailmerge_document_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument2
#define SOAP_TYPE_ns1__get_USCOREmailmerge_USCOREdocument2 (237)
/* ns1:get_mailmerge_document2 */
struct ns1__get_USCOREmailmerge_USCOREdocument2
{
	char *session;	/* optional element of type xsd:string */
	char *file_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *fields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREdocument_USCORErevisionResponse
#define SOAP_TYPE_ns1__get_USCOREdocument_USCORErevisionResponse (238)
/* ns1:get_document_revisionResponse */
struct ns1__get_USCOREdocument_USCORErevisionResponse
{
	struct ns1__return_USCOREdocument_USCORErevision *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:return_document_revision */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREdocument_USCORErevision
#define SOAP_TYPE_ns1__get_USCOREdocument_USCORErevision (242)
/* ns1:get_document_revision */
struct ns1__get_USCOREdocument_USCORErevision
{
	char *session;	/* optional element of type xsd:string */
	char *i;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmergeResponse
#define SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmergeResponse (243)
/* ns1:set_campaign_mergeResponse */
struct ns1__set_USCOREcampaign_USCOREmergeResponse
{
	struct ns1__error_USCOREvalue *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:error_value */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmerge
#define SOAP_TYPE_ns1__set_USCOREcampaign_USCOREmerge (246)
/* ns1:set_campaign_merge */
struct ns1__set_USCOREcampaign_USCOREmerge
{
	char *session;	/* optional element of type xsd:string */
	struct select_USCOREfields *targets;	/* optional element of type ArrayOfstring */
	char *campaign_USCOREid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries_USCOREcountResponse
#define SOAP_TYPE_ns1__get_USCOREentries_USCOREcountResponse (247)
/* ns1:get_entries_countResponse */
struct ns1__get_USCOREentries_USCOREcountResponse
{
	struct ns1__get_USCOREentries_USCOREcount_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entries_count_result */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREentries_USCOREcount
#define SOAP_TYPE_ns1__get_USCOREentries_USCOREcount (251)
/* ns1:get_entries_count */
struct ns1__get_USCOREentries_USCOREcount
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *query;	/* optional element of type xsd:string */
	int deleted;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries_USCOREdetailsResponse
#define SOAP_TYPE_ns1__set_USCOREentries_USCOREdetailsResponse (252)
/* ns1:set_entries_detailsResponse */
struct ns1__set_USCOREentries_USCOREdetailsResponse
{
	struct ns1__set_USCOREentries_USCOREdetail_USCOREresult *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:set_entries_detail_result */
};
#endif

#ifndef SOAP_TYPE_ns1__set_USCOREentries_USCOREdetails
#define SOAP_TYPE_ns1__set_USCOREentries_USCOREdetails (256)
/* ns1:set_entries_details */
struct ns1__set_USCOREentries_USCOREdetails
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists;	/* optional element of type ArrayOfArrayOfname-value */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__sync_USCOREget_USCOREmodified_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__sync_USCOREget_USCOREmodified_USCORErelationshipsResponse (257)
/* ns1:sync_get_modified_relationshipsResponse */
struct ns1__sync_USCOREget_USCOREmodified_USCORErelationshipsResponse
{
	struct ns1__get_USCOREentry_USCORElist_USCOREresult_USCOREencoded *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_entry_list_result_encoded */
};
#endif

#ifndef SOAP_TYPE_ns1__sync_USCOREget_USCOREmodified_USCORErelationships
#define SOAP_TYPE_ns1__sync_USCOREget_USCOREmodified_USCORErelationships (261)
/* ns1:sync_get_modified_relationships */
struct ns1__sync_USCOREget_USCOREmodified_USCORErelationships
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *related_USCOREmodule;	/* optional element of type xsd:string */
	char *from_USCOREdate;	/* optional element of type xsd:string */
	char *to_USCOREdate;	/* optional element of type xsd:string */
	int offset;	/* required element of type xsd:int */
	int max_USCOREresults;	/* required element of type xsd:int */
	int deleted;	/* required element of type xsd:int */
	char *module_USCOREid;	/* optional element of type xsd:string */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
	struct select_USCOREfields *ids;	/* optional element of type ArrayOfstring */
	char *relationship_USCOREname;	/* optional element of type xsd:string */
	char *deletion_USCOREdate;	/* optional element of type xsd:string */
	int php_USCOREserialize;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodified_USCOREentriesResponse
#define SOAP_TYPE_ns1__get_USCOREmodified_USCOREentriesResponse (262)
/* ns1:get_modified_entriesResponse */
struct ns1__get_USCOREmodified_USCOREentriesResponse
{
	struct ns1__get_USCOREsync_USCOREresult_USCOREencoded *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_sync_result_encoded */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREmodified_USCOREentries
#define SOAP_TYPE_ns1__get_USCOREmodified_USCOREentries (265)
/* ns1:get_modified_entries */
struct ns1__get_USCOREmodified_USCOREentries
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	struct select_USCOREfields *ids;	/* optional element of type ArrayOfstring */
	struct select_USCOREfields *select_USCOREfields;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREattendee_USCORElistResponse
#define SOAP_TYPE_ns1__get_USCOREattendee_USCORElistResponse (266)
/* ns1:get_attendee_listResponse */
struct ns1__get_USCOREattendee_USCORElistResponse
{
	struct ns1__get_USCOREsync_USCOREresult_USCOREencoded *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_sync_result_encoded */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREattendee_USCORElist
#define SOAP_TYPE_ns1__get_USCOREattendee_USCORElist (269)
/* ns1:get_attendee_list */
struct ns1__get_USCOREattendee_USCORElist
{
	char *session;	/* optional element of type xsd:string */
	char *module_USCOREname;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREsessionResponse
#define SOAP_TYPE_ns1__create_USCOREsessionResponse (271)
/* ns1:create_sessionResponse */
struct ns1__create_USCOREsessionResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREsession
#define SOAP_TYPE_ns1__create_USCOREsession (272)
/* ns1:create_session */
struct ns1__create_USCOREsession
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__end_USCOREsessionResponse
#define SOAP_TYPE_ns1__end_USCOREsessionResponse (274)
/* ns1:end_sessionResponse */
struct ns1__end_USCOREsessionResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__end_USCOREsession
#define SOAP_TYPE_ns1__end_USCOREsession (275)
/* ns1:end_session */
struct ns1__end_USCOREsession
{
	char *user_USCOREname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__contact_USCOREby_USCOREemailResponse
#define SOAP_TYPE_ns1__contact_USCOREby_USCOREemailResponse (276)
/* ns1:contact_by_emailResponse */
struct ns1__contact_USCOREby_USCOREemailResponse
{
	struct contact_USCOREdetail_USCOREarray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfcontact-detail */
};
#endif

#ifndef SOAP_TYPE_ns1__contact_USCOREby_USCOREemail
#define SOAP_TYPE_ns1__contact_USCOREby_USCOREemail (280)
/* ns1:contact_by_email */
struct ns1__contact_USCOREby_USCOREemail
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *email_USCOREaddress;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREcontact_USCORErelationshipsResponse
#define SOAP_TYPE_ns1__get_USCOREcontact_USCORErelationshipsResponse (281)
/* ns1:get_contact_relationshipsResponse */
struct ns1__get_USCOREcontact_USCORErelationshipsResponse
{
	struct contact_USCOREdetail_USCOREarray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfcontact-detail */
};
#endif

#ifndef SOAP_TYPE_ns1__get_USCOREcontact_USCORErelationships
#define SOAP_TYPE_ns1__get_USCOREcontact_USCORErelationships (284)
/* ns1:get_contact_relationships */
struct ns1__get_USCOREcontact_USCORErelationships
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__user_USCORElistResponse
#define SOAP_TYPE_ns1__user_USCORElistResponse (285)
/* ns1:user_listResponse */
struct ns1__user_USCORElistResponse
{
	struct user_USCOREdetail_USCOREarray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfuser-detail */
};
#endif

#ifndef SOAP_TYPE_ns1__user_USCORElist
#define SOAP_TYPE_ns1__user_USCORElist (289)
/* ns1:user_list */
struct ns1__user_USCORElist
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__searchResponse
#define SOAP_TYPE_ns1__searchResponse (290)
/* ns1:searchResponse */
struct ns1__searchResponse
{
	struct contact_USCOREdetail_USCOREarray *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfcontact-detail */
};
#endif

#ifndef SOAP_TYPE_ns1__search
#define SOAP_TYPE_ns1__search (293)
/* ns1:search */
struct ns1__search
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__track_USCOREemailResponse
#define SOAP_TYPE_ns1__track_USCOREemailResponse (295)
/* ns1:track_emailResponse */
struct ns1__track_USCOREemailResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__track_USCOREemail
#define SOAP_TYPE_ns1__track_USCOREemail (296)
/* ns1:track_email */
struct ns1__track_USCOREemail
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *parent_USCOREid;	/* optional element of type xsd:string */
	char *contact_USCOREids;	/* optional element of type xsd:string */
	char *date_USCOREsent;	/* optional element of type xsd:date */
	char *email_USCOREsubject;	/* optional element of type xsd:string */
	char *email_USCOREbody;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREcontactResponse
#define SOAP_TYPE_ns1__create_USCOREcontactResponse (298)
/* ns1:create_contactResponse */
struct ns1__create_USCOREcontactResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREcontact
#define SOAP_TYPE_ns1__create_USCOREcontact (299)
/* ns1:create_contact */
struct ns1__create_USCOREcontact
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *first_USCOREname;	/* optional element of type xsd:string */
	char *last_USCOREname;	/* optional element of type xsd:string */
	char *email_USCOREaddress;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREleadResponse
#define SOAP_TYPE_ns1__create_USCOREleadResponse (301)
/* ns1:create_leadResponse */
struct ns1__create_USCOREleadResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCORElead
#define SOAP_TYPE_ns1__create_USCORElead (302)
/* ns1:create_lead */
struct ns1__create_USCORElead
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *first_USCOREname;	/* optional element of type xsd:string */
	char *last_USCOREname;	/* optional element of type xsd:string */
	char *email_USCOREaddress;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREaccountResponse
#define SOAP_TYPE_ns1__create_USCOREaccountResponse (304)
/* ns1:create_accountResponse */
struct ns1__create_USCOREaccountResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREaccount
#define SOAP_TYPE_ns1__create_USCOREaccount (305)
/* ns1:create_account */
struct ns1__create_USCOREaccount
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
	char *phone;	/* optional element of type xsd:string */
	char *website;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREopportunityResponse
#define SOAP_TYPE_ns1__create_USCOREopportunityResponse (307)
/* ns1:create_opportunityResponse */
struct ns1__create_USCOREopportunityResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREopportunity
#define SOAP_TYPE_ns1__create_USCOREopportunity (308)
/* ns1:create_opportunity */
struct ns1__create_USCOREopportunity
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
	char *amount;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREcaseResponse
#define SOAP_TYPE_ns1__create_USCOREcaseResponse (310)
/* ns1:create_caseResponse */
struct ns1__create_USCOREcaseResponse
{
	char **return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREcase
#define SOAP_TYPE_ns1__create_USCOREcase (311)
/* ns1:create_case */
struct ns1__create_USCOREcase
{
	char *user_USCOREname;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (312)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (313)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (315)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (318)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (319)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (6)
typedef char *xsd__date;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns1__is_USCOREuser_USCOREadmin(struct soap*, char *session, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__login(struct soap*, struct ns1__user_USCOREauth *user_USCOREauth, char *application_USCOREname, struct ns1__loginResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 ns1__is_USCOREloopback(struct soap*, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__seamless_USCORElogin(struct soap*, char *session, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREentry_USCORElist(struct soap*, char *session, char *module_USCOREname, char *query, char *order_USCOREby, int offset, struct select_USCOREfields *select_USCOREfields, int max_USCOREresults, int deleted, struct ns1__get_USCOREentry_USCORElistResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREentry(struct soap*, char *session, char *module_USCOREname, char *id, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCOREentryResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREentries(struct soap*, char *session, char *module_USCOREname, struct select_USCOREfields *ids, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCOREentriesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCOREentry(struct soap*, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__set_USCOREentryResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCOREentries(struct soap*, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct ns1__set_USCOREentriesResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCOREnote_USCOREattachment(struct soap*, char *session, struct ns1__note_USCOREattachment *note, struct ns1__set_USCOREnote_USCOREattachmentResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREnote_USCOREattachment(struct soap*, char *session, char *id, struct ns1__get_USCOREnote_USCOREattachmentResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 ns1__relate_USCOREnote_USCOREto_USCOREmodule(struct soap*, char *session, char *note_USCOREid, char *module_USCOREname, char *module_USCOREid, struct ns1__relate_USCOREnote_USCOREto_USCOREmoduleResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCORErelated_USCOREnotes(struct soap*, char *session, char *module_USCOREname, char *module_USCOREid, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCORErelated_USCOREnotesResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 ns1__logout(struct soap*, char *session, struct ns1__logoutResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREmodule_USCOREfields(struct soap*, char *session, char *module_USCOREname, struct ns1__get_USCOREmodule_USCOREfieldsResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREavailable_USCOREmodules(struct soap*, char *session, struct ns1__get_USCOREavailable_USCOREmodulesResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 ns1__update_USCOREportal_USCOREuser(struct soap*, char *session, char *portal_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__update_USCOREportal_USCOREuserResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREuser_USCOREid(struct soap*, char *session, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREuser_USCOREteam_USCOREid(struct soap*, char *session, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREserver_USCOREtime(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREgmt_USCOREtime(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREsugar_USCOREflavor(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREserver_USCOREversion(struct soap*, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCORErelationships(struct soap*, char *session, char *module_USCOREname, char *module_USCOREid, char *related_USCOREmodule, char *related_USCOREmodule_USCOREquery, int deleted, struct ns1__get_USCORErelationshipsResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCORErelationship(struct soap*, char *session, struct ns1__set_USCORErelationship_USCOREvalue *set_USCORErelationship_USCOREvalue, struct ns1__set_USCORErelationshipResponse *_param_16);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCORErelationships(struct soap*, char *session, struct set_USCORErelationship_USCORElist *set_USCORErelationship_USCORElist, struct ns1__set_USCORErelationshipsResponse *_param_17);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCOREdocument_USCORErevision(struct soap*, char *session, struct ns1__document_USCORErevision *note, struct ns1__set_USCOREdocument_USCORErevisionResponse *_param_18);

SOAP_FMAC5 int SOAP_FMAC6 ns1__search_USCOREby_USCOREmodule(struct soap*, char *user_USCOREname, char *password, char *search_USCOREstring, struct select_USCOREfields *modules, int offset, int max_USCOREresults, struct ns1__search_USCOREby_USCOREmoduleResponse *_param_19);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREmailmerge_USCOREdocument(struct soap*, char *session, char *file_USCOREname, struct select_USCOREfields *fields, struct ns1__get_USCOREmailmerge_USCOREdocumentResponse *_param_20);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREmailmerge_USCOREdocument2(struct soap*, char *session, char *file_USCOREname, struct select_USCOREfields *fields, struct ns1__get_USCOREmailmerge_USCOREdocument2Response *_param_21);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREdocument_USCORErevision(struct soap*, char *session, char *i, struct ns1__get_USCOREdocument_USCORErevisionResponse *_param_22);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCOREcampaign_USCOREmerge(struct soap*, char *session, struct select_USCOREfields *targets, char *campaign_USCOREid, struct ns1__set_USCOREcampaign_USCOREmergeResponse *_param_23);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREentries_USCOREcount(struct soap*, char *session, char *module_USCOREname, char *query, int deleted, struct ns1__get_USCOREentries_USCOREcountResponse *_param_24);

SOAP_FMAC5 int SOAP_FMAC6 ns1__set_USCOREentries_USCOREdetails(struct soap*, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct select_USCOREfields *select_USCOREfields, struct ns1__set_USCOREentries_USCOREdetailsResponse *_param_25);

SOAP_FMAC5 int SOAP_FMAC6 ns1__sync_USCOREget_USCOREmodified_USCORErelationships(struct soap*, char *session, char *module_USCOREname, char *related_USCOREmodule, char *from_USCOREdate, char *to_USCOREdate, int offset, int max_USCOREresults, int deleted, char *module_USCOREid, struct select_USCOREfields *select_USCOREfields, struct select_USCOREfields *ids, char *relationship_USCOREname, char *deletion_USCOREdate, int php_USCOREserialize, struct ns1__sync_USCOREget_USCOREmodified_USCORErelationshipsResponse *_param_26);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREmodified_USCOREentries(struct soap*, char *session, char *module_USCOREname, struct select_USCOREfields *ids, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCOREmodified_USCOREentriesResponse *_param_27);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREattendee_USCORElist(struct soap*, char *session, char *module_USCOREname, char *id, struct ns1__get_USCOREattendee_USCORElistResponse *_param_28);

SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCOREsession(struct soap*, char *user_USCOREname, char *password, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__end_USCOREsession(struct soap*, char *user_USCOREname, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__contact_USCOREby_USCOREemail(struct soap*, char *user_USCOREname, char *password, char *email_USCOREaddress, struct ns1__contact_USCOREby_USCOREemailResponse *_param_29);

SOAP_FMAC5 int SOAP_FMAC6 ns1__get_USCOREcontact_USCORErelationships(struct soap*, char *user_USCOREname, char *password, char *id, struct ns1__get_USCOREcontact_USCORErelationshipsResponse *_param_30);

SOAP_FMAC5 int SOAP_FMAC6 ns1__user_USCORElist(struct soap*, char *user_USCOREname, char *password, struct ns1__user_USCORElistResponse *_param_31);

SOAP_FMAC5 int SOAP_FMAC6 ns1__search(struct soap*, char *user_USCOREname, char *password, char *name, struct ns1__searchResponse *_param_32);

SOAP_FMAC5 int SOAP_FMAC6 ns1__track_USCOREemail(struct soap*, char *user_USCOREname, char *password, char *parent_USCOREid, char *contact_USCOREids, char *date_USCOREsent, char *email_USCOREsubject, char *email_USCOREbody, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCOREcontact(struct soap*, char *user_USCOREname, char *password, char *first_USCOREname, char *last_USCOREname, char *email_USCOREaddress, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCORElead(struct soap*, char *user_USCOREname, char *password, char *first_USCOREname, char *last_USCOREname, char *email_USCOREaddress, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCOREaccount(struct soap*, char *user_USCOREname, char *password, char *name, char *phone, char *website, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCOREopportunity(struct soap*, char *user_USCOREname, char *password, char *name, char *amount, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCOREcase(struct soap*, char *user_USCOREname, char *password, char *name, char **return_);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__is_USCOREuser_USCOREadmin(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__user_USCOREauth *user_USCOREauth, char *application_USCOREname, struct ns1__loginResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__is_USCOREloopback(struct soap *soap, const char *soap_endpoint, const char *soap_action, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__seamless_USCORElogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, int *return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentry_USCORElist(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *query, char *order_USCOREby, int offset, struct select_USCOREfields *select_USCOREfields, int max_USCOREresults, int deleted, struct ns1__get_USCOREentry_USCORElistResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *id, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCOREentryResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct select_USCOREfields *ids, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCOREentriesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentry(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__set_USCOREentryResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct ns1__set_USCOREentriesResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREnote_USCOREattachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__note_USCOREattachment *note, struct ns1__set_USCOREnote_USCOREattachmentResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREnote_USCOREattachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *id, struct ns1__get_USCOREnote_USCOREattachmentResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__relate_USCOREnote_USCOREto_USCOREmodule(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *note_USCOREid, char *module_USCOREname, char *module_USCOREid, struct ns1__relate_USCOREnote_USCOREto_USCOREmoduleResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCORErelated_USCOREnotes(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *module_USCOREid, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCORErelated_USCOREnotesResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__logoutResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodule_USCOREfields(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct ns1__get_USCOREmodule_USCOREfieldsResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREavailable_USCOREmodules(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__get_USCOREavailable_USCOREmodulesResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__update_USCOREportal_USCOREuser(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *portal_USCOREname, struct name_USCOREvalue_USCORElist *name_USCOREvalue_USCORElist, struct ns1__update_USCOREportal_USCOREuserResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREuser_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREuser_USCOREteam_USCOREid(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREserver_USCOREtime(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREgmt_USCOREtime(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREsugar_USCOREflavor(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREserver_USCOREversion(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *module_USCOREid, char *related_USCOREmodule, char *related_USCOREmodule_USCOREquery, int deleted, struct ns1__get_USCORErelationshipsResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCORErelationship(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__set_USCORErelationship_USCOREvalue *set_USCORErelationship_USCOREvalue, struct ns1__set_USCORErelationshipResponse *_param_16);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct set_USCORErelationship_USCORElist *set_USCORErelationship_USCORElist, struct ns1__set_USCORErelationshipsResponse *_param_17);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREdocument_USCORErevision(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct ns1__document_USCORErevision *note, struct ns1__set_USCOREdocument_USCORErevisionResponse *_param_18);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__search_USCOREby_USCOREmodule(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *search_USCOREstring, struct select_USCOREfields *modules, int offset, int max_USCOREresults, struct ns1__search_USCOREby_USCOREmoduleResponse *_param_19);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmailmerge_USCOREdocument(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *file_USCOREname, struct select_USCOREfields *fields, struct ns1__get_USCOREmailmerge_USCOREdocumentResponse *_param_20);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmailmerge_USCOREdocument2(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *file_USCOREname, struct select_USCOREfields *fields, struct ns1__get_USCOREmailmerge_USCOREdocument2Response *_param_21);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREdocument_USCORErevision(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *i, struct ns1__get_USCOREdocument_USCORErevisionResponse *_param_22);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREcampaign_USCOREmerge(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, struct select_USCOREfields *targets, char *campaign_USCOREid, struct ns1__set_USCOREcampaign_USCOREmergeResponse *_param_23);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREentries_USCOREcount(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *query, int deleted, struct ns1__get_USCOREentries_USCOREcountResponse *_param_24);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__set_USCOREentries_USCOREdetails(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct name_USCOREvalue_USCORElists *name_USCOREvalue_USCORElists, struct select_USCOREfields *select_USCOREfields, struct ns1__set_USCOREentries_USCOREdetailsResponse *_param_25);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sync_USCOREget_USCOREmodified_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *related_USCOREmodule, char *from_USCOREdate, char *to_USCOREdate, int offset, int max_USCOREresults, int deleted, char *module_USCOREid, struct select_USCOREfields *select_USCOREfields, struct select_USCOREfields *ids, char *relationship_USCOREname, char *deletion_USCOREdate, int php_USCOREserialize, struct ns1__sync_USCOREget_USCOREmodified_USCORErelationshipsResponse *_param_26);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREmodified_USCOREentries(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, struct select_USCOREfields *ids, struct select_USCOREfields *select_USCOREfields, struct ns1__get_USCOREmodified_USCOREentriesResponse *_param_27);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREattendee_USCORElist(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *session, char *module_USCOREname, char *id, struct ns1__get_USCOREattendee_USCORElistResponse *_param_28);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCOREsession(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__end_USCOREsession(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__contact_USCOREby_USCOREemail(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *email_USCOREaddress, struct ns1__contact_USCOREby_USCOREemailResponse *_param_29);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__get_USCOREcontact_USCORErelationships(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *id, struct ns1__get_USCOREcontact_USCORErelationshipsResponse *_param_30);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__user_USCORElist(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, struct ns1__user_USCORElistResponse *_param_31);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__search(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *name, struct ns1__searchResponse *_param_32);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__track_USCOREemail(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *parent_USCOREid, char *contact_USCOREids, char *date_USCOREsent, char *email_USCOREsubject, char *email_USCOREbody, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCOREcontact(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *first_USCOREname, char *last_USCOREname, char *email_USCOREaddress, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCORElead(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *first_USCOREname, char *last_USCOREname, char *email_USCOREaddress, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCOREaccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *name, char *phone, char *website, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCOREopportunity(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *name, char *amount, char **return_);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCOREcase(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *user_USCOREname, char *password, char *name, char **return_);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__is_USCOREuser_USCOREadmin(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__login(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__is_USCOREloopback(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__seamless_USCORElogin(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREentry_USCORElist(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREentry(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREentries(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCOREentry(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCOREentries(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCOREnote_USCOREattachment(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREnote_USCOREattachment(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__relate_USCOREnote_USCOREto_USCOREmodule(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCORErelated_USCOREnotes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__logout(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREmodule_USCOREfields(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREavailable_USCOREmodules(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__update_USCOREportal_USCOREuser(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREuser_USCOREid(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREuser_USCOREteam_USCOREid(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREserver_USCOREtime(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREgmt_USCOREtime(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREsugar_USCOREflavor(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREserver_USCOREversion(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCORErelationships(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCORErelationship(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCORErelationships(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCOREdocument_USCORErevision(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__search_USCOREby_USCOREmodule(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREmailmerge_USCOREdocument(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREmailmerge_USCOREdocument2(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREdocument_USCORErevision(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCOREcampaign_USCOREmerge(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREentries_USCOREcount(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__set_USCOREentries_USCOREdetails(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__sync_USCOREget_USCOREmodified_USCORErelationships(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREmodified_USCOREentries(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREattendee_USCORElist(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREsession(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__end_USCOREsession(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__contact_USCOREby_USCOREemail(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__get_USCOREcontact_USCORErelationships(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__user_USCORElist(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__search(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__track_USCOREemail(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREcontact(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCORElead(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREaccount(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREopportunity(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREcase(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
